## Configuração — Imports e Conexão

In [1]:
from pymongo import MongoClient
from datetime import datetime
import pandas as pd

client = MongoClient("mongodb://root:rootpass@localhost:27017")
db = client['clinica_veterinaria']
print(client.server_info()["version"])

8.2.6

## 1. Inserir os 50 registros

In [2]:
db.atendimentos.drop()

atendimentos = [
    {"tutor":"Ana","animal":"Cachorro","nome_pet":"Rex1","servico":"Consulta","valor":120,"cidade":"Assis","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
    {"tutor":"Bruno","animal":"Gato","nome_pet":"Mimi2","servico":"Vacinação","valor":95,"cidade":"Assis","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
    {"tutor":"Carlos","animal":"Cachorro","nome_pet":"Thor3","servico":"Banho","valor":60,"cidade":"Assis","data":datetime(2026,3,3),"forma_pagamento":"Dinheiro"},
    {"tutor":"Daniela","animal":"Ave","nome_pet":"Piu4","servico":"Exame","valor":180,"cidade":"Assis","data":datetime(2026,3,4),"forma_pagamento":"Cartão"},
    {"tutor":"Eduardo","animal":"Gato","nome_pet":"Luna5","servico":"Consulta","valor":130,"cidade":"Assis","data":datetime(2026,3,5),"forma_pagamento":"Pix"},
    {"tutor":"Fernanda","animal":"Cachorro","nome_pet":"Bob6","servico":"Vacinação","valor":90,"cidade":"Assis","data":datetime(2026,3,6),"forma_pagamento":"Dinheiro"},
    {"tutor":"Gabriel","animal":"Coelho","nome_pet":"Pompom7","servico":"Consulta","valor":110,"cidade":"Assis","data":datetime(2026,3,7),"forma_pagamento":"Pix"},
    {"tutor":"Helena","animal":"Cachorro","nome_pet":"Mel8","servico":"Cirurgia","valor":820,"cidade":"Assis","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
    {"tutor":"Igor","animal":"Gato","nome_pet":"Simba9","servico":"Banho","valor":55,"cidade":"Assis","data":datetime(2026,3,9),"forma_pagamento":"Cartão"},
    {"tutor":"Juliana","animal":"Cachorro","nome_pet":"Nina10","servico":"Consulta","valor":125,"cidade":"Assis","data":datetime(2026,3,10),"forma_pagamento":"Pix"},
    {"tutor":"Lucas","animal":"Ave","nome_pet":"Sky11","servico":"Exame","valor":200,"cidade":"Assis","data":datetime(2026,3,11),"forma_pagamento":"Cartão"},
    {"tutor":"Mariana","animal":"Gato","nome_pet":"Lili12","servico":"Consulta","valor":135,"cidade":"Assis","data":datetime(2026,3,12),"forma_pagamento":"Pix"},
    {"tutor":"Nicolas","animal":"Cachorro","nome_pet":"Bolt13","servico":"Vacinação","valor":100,"cidade":"Assis","data":datetime(2026,3,13),"forma_pagamento":"Dinheiro"},
    {"tutor":"Patricia","animal":"Cachorro","nome_pet":"Max14","servico":"Consulta","valor":140,"cidade":"Ourinhos","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
    {"tutor":"Rafael","animal":"Gato","nome_pet":"Mia15","servico":"Banho","valor":65,"cidade":"Ourinhos","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
    {"tutor":"Sofia","animal":"Cachorro","nome_pet":"Luna16","servico":"Cirurgia","valor":900,"cidade":"Ourinhos","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
    {"tutor":"Thiago","animal":"Ave","nome_pet":"Blue17","servico":"Exame","valor":170,"cidade":"Ourinhos","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
    {"tutor":"Vanessa","animal":"Gato","nome_pet":"Nino18","servico":"Consulta","valor":125,"cidade":"Ourinhos","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
    {"tutor":"William","animal":"Cachorro","nome_pet":"Thor19","servico":"Vacinação","valor":95,"cidade":"Ourinhos","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
    {"tutor":"Beatriz","animal":"Coelho","nome_pet":"Fluffy20","servico":"Consulta","valor":115,"cidade":"Ourinhos","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
    {"tutor":"Caio","animal":"Cachorro","nome_pet":"Spike21","servico":"Banho","valor":70,"cidade":"Ourinhos","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
    {"tutor":"Diego","animal":"Gato","nome_pet":"Tom22","servico":"Consulta","valor":135,"cidade":"Ourinhos","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
    {"tutor":"Elisa","animal":"Cachorro","nome_pet":"Mel23","servico":"Exame","valor":210,"cidade":"Ourinhos","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
    {"tutor":"Felipe","animal":"Ave","nome_pet":"Kiwi24","servico":"Consulta","valor":120,"cidade":"Ourinhos","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
    {"tutor":"Gisele","animal":"Gato","nome_pet":"Nina25","servico":"Vacinação","valor":85,"cidade":"Ourinhos","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
    {"tutor":"Hugo","animal":"Cachorro","nome_pet":"Rex26","servico":"Consulta","valor":150,"cidade":"Ourinhos","data":datetime(2026,3,13),"forma_pagamento":"Cartão"},
    {"tutor":"Iris","animal":"Cachorro","nome_pet":"Bob27","servico":"Consulta","valor":110,"cidade":"Pompeia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
    {"tutor":"Joao","animal":"Gato","nome_pet":"Luna28","servico":"Banho","valor":60,"cidade":"Pompeia","data":datetime(2026,3,2),"forma_pagamento":"Dinheiro"},
    {"tutor":"Karen","animal":"Cachorro","nome_pet":"Thor29","servico":"Cirurgia","valor":780,"cidade":"Pompeia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
    {"tutor":"Leo","animal":"Ave","nome_pet":"Sky30","servico":"Exame","valor":160,"cidade":"Pompeia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
    {"tutor":"Marta","animal":"Gato","nome_pet":"Mimi31","servico":"Consulta","valor":120,"cidade":"Pompeia","data":datetime(2026,3,5),"forma_pagamento":"Cartão"},
    {"tutor":"Nelson","animal":"Cachorro","nome_pet":"Max32","servico":"Vacinação","valor":90,"cidade":"Pompeia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
    {"tutor":"Olga","animal":"Coelho","nome_pet":"Pompom33","servico":"Consulta","valor":105,"cidade":"Pompeia","data":datetime(2026,3,7),"forma_pagamento":"Dinheiro"},
    {"tutor":"Paulo","animal":"Cachorro","nome_pet":"Bolt34","servico":"Banho","valor":75,"cidade":"Pompeia","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
    {"tutor":"Quezia","animal":"Gato","nome_pet":"Simba35","servico":"Consulta","valor":130,"cidade":"Pompeia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
    {"tutor":"Renato","animal":"Cachorro","nome_pet":"Nina36","servico":"Exame","valor":190,"cidade":"Pompeia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
    {"tutor":"Sara","animal":"Ave","nome_pet":"Blue37","servico":"Consulta","valor":115,"cidade":"Pompeia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
    {"tutor":"Tiago","animal":"Gato","nome_pet":"Lili38","servico":"Vacinação","valor":85,"cidade":"Pompeia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
    {"tutor":"Ursula","animal":"Cachorro","nome_pet":"Rex39","servico":"Consulta","valor":145,"cidade":"Marilia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
    {"tutor":"Vitor","animal":"Gato","nome_pet":"Mia40","servico":"Banho","valor":70,"cidade":"Marilia","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
    {"tutor":"Wesley","animal":"Cachorro","nome_pet":"Thor41","servico":"Cirurgia","valor":870,"cidade":"Marilia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
    {"tutor":"Xuxa","animal":"Ave","nome_pet":"Piu42","servico":"Exame","valor":175,"cidade":"Marilia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
    {"tutor":"Yara","animal":"Gato","nome_pet":"Luna43","servico":"Consulta","valor":135,"cidade":"Marilia","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
    {"tutor":"Zeca","animal":"Cachorro","nome_pet":"Bob44","servico":"Vacinação","valor":100,"cidade":"Marilia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
    {"tutor":"Aline","animal":"Coelho","nome_pet":"Fluffy45","servico":"Consulta","valor":120,"cidade":"Marilia","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
    {"tutor":"Bruna","animal":"Cachorro","nome_pet":"Spike46","servico":"Banho","valor":80,"cidade":"Marilia","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
    {"tutor":"Cesar","animal":"Gato","nome_pet":"Tom47","servico":"Consulta","valor":140,"cidade":"Marilia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
    {"tutor":"Dora","animal":"Cachorro","nome_pet":"Mel48","servico":"Exame","valor":220,"cidade":"Marilia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
    {"tutor":"Enzo","animal":"Ave","nome_pet":"Kiwi49","servico":"Consulta","valor":130,"cidade":"Marilia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
    {"tutor":"Fabio","animal":"Gato","nome_pet":"Nina50","servico":"Vacinação","valor":90,"cidade":"Marilia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
]

result = db.atendimentos.insert_many(atendimentos)
print(f'{len(result.inserted_ids)} registros inseridos')

50 registros inseridos

## 2. Atendimentos com valor entre R$90 e R$200

In [3]:
df_90_200 = pd.DataFrame(list(db.atendimentos.find({"valor": {"$gte": 90, "$lte": 200}}, {"_id": 0})))
print(f'{len(df_90_200)} atendimentos entre R$90 e R$200')
df_90_200

34 atendimentos entre R$90 e R$200

,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
2,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
3,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix
4,Fernanda,Cachorro,Bob6,Vacinação,90,Assis,2026-03-06,Dinheiro
5,Gabriel,Coelho,Pompom7,Consulta,110,Assis,2026-03-07,Pix
6,Juliana,Cachorro,Nina10,Consulta,125,Assis,2026-03-10,Pix
7,Lucas,Ave,Sky11,Exame,200,Assis,2026-03-11,Cartão
8,Mariana,Gato,Lili12,Consulta,135,Assis,2026-03-12,Pix
9,Nicolas,Cachorro,Bolt13,Vacinação,100,Assis,2026-03-13,Dinheiro
10,Patricia,Cachorro,Max14,Consulta,140,Ourinhos,2026-03-01,Pix
11,Thiago,Ave,Blue17,Exame,170,Ourinhos,2026-03-04,Pix
12,Vanessa,Gato,Nino18,Consulta,125,Ourinhos,2026-03-05,Dinheiro
13,William,Cachorro,Thor19,Vacinação,95,Ourinhos,2026-03-06,Pix
14,Beatriz,Coelho,Fluffy20,Consulta,115,Ourinhos,2026-03-07,Cartão
15,Diego,Gato,Tom22,Consulta,135,Ourinhos,2026-03-09,Pix
16,Felipe,Ave,Kiwi24,Consulta,120,Ourinhos,2026-03-11,Pix
17,Hugo,Cachorro,Rex26,Consulta,150,Ourinhos,2026-03-13,Cartão
18,Iris,Cachorro,Bob27,Consulta,110,Pompeia,2026-03-01,Pix
19,Leo,Ave,Sky30,Exame,160,Pompeia,2026-03-04,Pix
20,Marta,Gato,Mimi31,Consulta,120,Pompeia,2026-03-05,Cartão
21,Nelson,Cachorro,Max32,Vacinação,90,Pompeia,2026-03-06,Pix
22,Olga,Coelho,Pompom33,Consulta,105,Pompeia,2026-03-07,Dinheiro
23,Quezia,Gato,Simba35,Consulta,130,Pompeia,2026-03-09,Pix
24,Renato,Cachorro,Nina36,Exame,190,Pompeia,2026-03-10,Cartão
25,Sara,Ave,Blue37,Consulta,115,Pompeia,2026-03-11,Pix
26,Ursula,Cachorro,Rex39,Consulta,145,Marilia,2026-03-01,Pix
27,Xuxa,Ave,Piu42,Exame,175,Marilia,2026-03-04,Pix
28,Yara,Gato,Luna43,Consulta,135,Marilia,2026-03-05,Dinheiro
29,Zeca,Cachorro,Bob44,Vacinação,100,Marilia,2026-03-06,Pix
30,Aline,Coelho,Fluffy45,Consulta,120,Marilia,2026-03-07,Cartão
31,Cesar,Gato,Tom47,Consulta,140,Marilia,2026-03-09,Pix
32,Enzo,Ave,Kiwi49,Consulta,130,Marilia,2026-03-11,Pix
33,Fabio,Gato,Nina50,Vacinação,90,Marilia,2026-03-12,Dinheiro

## 3. Atendimentos das cidades Assis, Ourinhos, Pompeia e Marília

In [4]:
df_cidades = pd.DataFrame(list(db.atendimentos.find({"cidade": {"$in": ["Assis", "Ourinhos", "Pompeia", "Marilia"]}}, {"_id": 0})))
print(f'{len(df_cidades)} atendimentos encontrados')
df_cidades

50 atendimentos encontrados

,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
2,Carlos,Cachorro,Thor3,Banho,60,Assis,2026-03-03,Dinheiro
3,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
4,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix
5,Fernanda,Cachorro,Bob6,Vacinação,90,Assis,2026-03-06,Dinheiro
6,Gabriel,Coelho,Pompom7,Consulta,110,Assis,2026-03-07,Pix
7,Helena,Cachorro,Mel8,Cirurgia,820,Assis,2026-03-08,Cartão
8,Igor,Gato,Simba9,Banho,55,Assis,2026-03-09,Cartão
9,Juliana,Cachorro,Nina10,Consulta,125,Assis,2026-03-10,Pix
10,Lucas,Ave,Sky11,Exame,200,Assis,2026-03-11,Cartão
11,Mariana,Gato,Lili12,Consulta,135,Assis,2026-03-12,Pix
12,Nicolas,Cachorro,Bolt13,Vacinação,100,Assis,2026-03-13,Dinheiro
13,Patricia,Cachorro,Max14,Consulta,140,Ourinhos,2026-03-01,Pix
14,Rafael,Gato,Mia15,Banho,65,Ourinhos,2026-03-02,Cartão
15,Sofia,Cachorro,Luna16,Cirurgia,900,Ourinhos,2026-03-03,Cartão
16,Thiago,Ave,Blue17,Exame,170,Ourinhos,2026-03-04,Pix
17,Vanessa,Gato,Nino18,Consulta,125,Ourinhos,2026-03-05,Dinheiro
18,William,Cachorro,Thor19,Vacinação,95,Ourinhos,2026-03-06,Pix
19,Beatriz,Coelho,Fluffy20,Consulta,115,Ourinhos,2026-03-07,Cartão
20,Caio,Cachorro,Spike21,Banho,70,Ourinhos,2026-03-08,Dinheiro
21,Diego,Gato,Tom22,Consulta,135,Ourinhos,2026-03-09,Pix
22,Elisa,Cachorro,Mel23,Exame,210,Ourinhos,2026-03-10,Cartão
23,Felipe,Ave,Kiwi24,Consulta,120,Ourinhos,2026-03-11,Pix
24,Gisele,Gato,Nina25,Vacinação,85,Ourinhos,2026-03-12,Dinheiro
25,Hugo,Cachorro,Rex26,Consulta,150,Ourinhos,2026-03-13,Cartão
26,Iris,Cachorro,Bob27,Consulta,110,Pompeia,2026-03-01,Pix
27,Joao,Gato,Luna28,Banho,60,Pompeia,2026-03-02,Dinheiro
28,Karen,Cachorro,Thor29,Cirurgia,780,Pompeia,2026-03-03,Cartão
29,Leo,Ave,Sky30,Exame,160,Pompeia,2026-03-04,Pix
30,Marta,Gato,Mimi31,Consulta,120,Pompeia,2026-03-05,Cartão
31,Nelson,Cachorro,Max32,Vacinação,90,Pompeia,2026-03-06,Pix
32,Olga,Coelho,Pompom33,Consulta,105,Pompeia,2026-03-07,Dinheiro
33,Paulo,Cachorro,Bolt34,Banho,75,Pompeia,2026-03-08,Cartão
34,Quezia,Gato,Simba35,Consulta,130,Pompeia,2026-03-09,Pix
35,Renato,Cachorro,Nina36,Exame,190,Pompeia,2026-03-10,Cartão
36,Sara,Ave,Blue37,Consulta,115,Pompeia,2026-03-11,Pix
37,Tiago,Gato,Lili38,Vacinação,85,Pompeia,2026-03-12,Dinheiro
38,Ursula,Cachorro,Rex39,Consulta,145,Marilia,2026-03-01,Pix
39,Vitor,Gato,Mia40,Banho,70,Marilia,2026-03-02,Cartão
40,Wesley,Cachorro,Thor41,Cirurgia,870,Marilia,2026-03-03,Cartão
41,Xuxa,Ave,Piu42,Exame,175,Marilia,2026-03-04,Pix
42,Yara,Gato,Luna43,Consulta,135,Marilia,2026-03-05,Dinheiro
43,Zeca,Cachorro,Bob44,Vacinação,100,Marilia,2026-03-06,Pix
44,Aline,Coelho,Fluffy45,Consulta,120,Marilia,2026-03-07,Cartão
45,Bruna,Cachorro,Spike46,Banho,80,Marilia,2026-03-08,Dinheiro
46,Cesar,Gato,Tom47,Consulta,140,Marilia,2026-03-09,Pix
47,Dora,Cachorro,Mel48,Exame,220,Marilia,2026-03-10,Cartão
48,Enzo,Ave,Kiwi49,Consulta,130,Marilia,2026-03-11,Pix
49,Fabio,Gato,Nina50,Vacinação,90,Marilia,2026-03-12,Dinheiro

## 4. Converter resultados para DataFrame

In [5]:
df = pd.DataFrame(list(db.atendimentos.find({}, {"_id": 0})))
print(f'DataFrame com {len(df)} registros e {len(df.columns)} colunas')
df.head()

DataFrame com 50 registros e 8 colunas

,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
2,Carlos,Cachorro,Thor3,Banho,60,Assis,2026-03-03,Dinheiro
3,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
4,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix

## 5. Verificar valores nulos

In [6]:
print(df.isnull().sum())

tutor              0
animal             0
nome_pet           0
servico            0
valor              0
cidade             0
data               0
forma_pagamento    0
dtype: int64

## 6. Faturamento total

In [7]:
faturamento_total = df['valor'].sum()
print(f'Faturamento total: R${faturamento_total:.2f}')

Faturamento total: R$8895.00

## 7. Faturamento por cidade

In [8]:
faturamento_por_cidade = df.groupby('cidade')['valor'].sum().to_dict()
print(faturamento_por_cidade)

{'Assis': 2220, 'Marilia': 2275, 'Ourinhos': 2380, 'Pompeia': 2020}

## 8. Faturamento por serviço

In [9]:
faturamento_por_servico = df.groupby('servico')['valor'].sum().to_dict()
print(faturamento_por_servico)

{'Banho': 535, 'Cirurgia': 3370, 'Consulta': 2655, 'Exame': 1505, 'Vacinação': 830}

## 9. Ticket médio geral

In [10]:
ticket_medio_geral = df['valor'].mean()
print(f'Ticket médio geral: R${ticket_medio_geral:.2f}')

Ticket médio geral: R$177.90

## 10. Ticket médio por cidade

In [11]:
ticket_medio_por_cidade = df.groupby('cidade')['valor'].mean().to_dict()
print(ticket_medio_por_cidade)

{'Assis': 170.76923076923077, 'Marilia': 189.58333333333334, 'Ourinhos': 183.07692307692307, 'Pompeia': 168.33333333333334}

## 11. Serviço mais lucrativo

In [12]:
servico_mais_lucrativo = max(faturamento_por_servico, key=faturamento_por_servico.get)
print(f'Serviço mais lucrativo: {servico_mais_lucrativo} (R${faturamento_por_servico[servico_mais_lucrativo]:.2f})')

Serviço mais lucrativo: Cirurgia (R$3370.00)

## 12. Cidade com maior faturamento

In [13]:
cidade_maior_faturamento = max(faturamento_por_cidade, key=faturamento_por_cidade.get)
print(f'Cidade com maior faturamento: {cidade_maior_faturamento} (R${faturamento_por_cidade[cidade_maior_faturamento]:.2f})')

Cidade com maior faturamento: Ourinhos (R$2380.00)

## 13. Top 3 maiores atendimentos

In [14]:
top3 = df.nlargest(3, 'valor')[['tutor', 'nome_pet', 'servico', 'valor', 'cidade']]
print(top3)

     tutor nome_pet   servico  valor    cidade
15   Sofia   Luna16  Cirurgia    900  Ourinhos
40  Wesley   Thor41  Cirurgia    870   Marilia
7   Helena     Mel8  Cirurgia    820     Assis

## Relatório Final — Geração e Salvamento no MongoDB

In [15]:
relatorio = {
    "data_geracao": datetime.now(),
    "faturamento_total": float(faturamento_total),
    "faturamento_por_cidade": {k: float(v) for k, v in faturamento_por_cidade.items()},
    "faturamento_por_servico": {k: float(v) for k, v in faturamento_por_servico.items()},
    "ticket_medio_geral": float(ticket_medio_geral),
    "ticket_medio_por_cidade": {k: float(v) for k, v in ticket_medio_por_cidade.items()},
    "servico_mais_lucrativo": servico_mais_lucrativo,
    "cidade_maior_faturamento": cidade_maior_faturamento,
    "top_3_atendimentos": df.nlargest(3, 'valor').drop(columns=['data']).to_dict(orient='records')
}

db.relatorios.insert_one(relatorio)
relatorio.pop('_id', None)
print(relatorio)

{'data_geracao': datetime.datetime(2026, 3, 25, 23, 27, 6, 590133), 'faturamento_total': 8895.0, 'faturamento_por_cidade': {'Assis': 2220.0, 'Marilia': 2275.0, 'Ourinhos': 2380.0, 'Pompeia': 2020.0}, 'faturamento_por_servico': {'Banho': 535.0, 'Cirurgia': 3370.0, 'Consulta': 2655.0, 'Exame': 1505.0, 'Vacinação': 830.0}, 'ticket_medio_geral': 177.9, 'ticket_medio_por_cidade': {'Assis': 170.76923076923077, 'Marilia': 189.58333333333334, 'Ourinhos': 183.07692307692307, 'Pompeia': 168.33333333333334}, 'servico_mais_lucrativo': 'Cirurgia', 'cidade_maior_faturamento': 'Ourinhos', 'top_3_atendimentos': [{'tutor': 'Sofia', 'animal': 'Cachorro', 'nome_pet': 'Luna16', 'servico': 'Cirurgia', 'valor': 900, 'cidade': 'Ourinhos', 'forma_pagamento': 'Cartão'}, {'tutor': 'Wesley', 'animal': 'Cachorro', 'nome_pet': 'Thor41', 'servico': 'Cirurgia', 'valor': 870, 'cidade': 'Marilia', 'forma_pagamento': 'Cartão'}, {'tutor': 'Helena', 'animal': 'Cachorro', 'nome_pet': 'Mel8', 'servico': 'Cirurgia', 'valor': 820, 'cidade': 'Assis', 'forma_pagamento': 'Cartão'}]}